name: Worlds
main: surva\worlds\Worlds
version: 2.0.3
api: 3.0.0

author: survanetwork

commands:
  worlds:
    description: ""
    usage: "/worlds list\n/worlds create <worldname> [type]\n/worlds <remove|load|unload|tp> <worldname>\n/worlds <copy|rename> <from> <to>\n/worlds set\n/worlds set permission <permissionstring>\n/worlds set gamemode <survival|creative|adventure|spectator>\n/worlds set <build|pvp|damage|drop|hunger|fly> <true|false>\n/worlds unset <permission|gamemode|build|pvp|damage|drop|hunger|fly>"
    aliases: ["ws"]
permissions:
  worlds.list:
    description: ""
    default: true
  worlds.admin:
    description: ""
    default: op
    children:
      worlds.admin.create:
        description: ""
        default: op
      worlds.admin.remove:
        description: ""
        default: op
      worlds.admin.copy:
        description: ""
        default: op
      worlds.admin.rename:
        description: ""
        default: op
      worlds.admin.load:
        description: ""
        default: op
      worlds.admin.unload:
        description: ""
        default: op
      worlds.admin.teleport:
        description: ""
        default: op
      worlds.admin.set:
        description: "
        default: op
      worlds.admin.unset:
        description: ""
        default: op
      worlds.admin.build:
        description: ""
        default: op
      worlds.admin.interact:
        description: ""
        default: op
      worlds.admin.gamemode:
        description: ""
        default: false
      worlds.admin.fly:
        description: ""
        default: false
